#ifndef OBSERVABLE_COMMAND_H
#define OBSERVABLE_COMMAND_H

enum OBSERVABLE_COMMAND {
    SHOW_QR,
    LOGIN_SUCCESS,
    HISTORICAL_MESSAGE_RECEIVED,
    CONTACT_RECEIVED,
    CHAT_RECEIVED,
    NEW_MESSAGE
};

#endif // OBSERVABLE_COMMAND_H
